### ISSUE TITLE
Project lookup

### ISSUE THREAD

**Issue by Watchful1** [amcoder/Curse.RestProxy#1]
I'm completely unfamiliar with the existing functionalities of the curse api, but would it be possible to add support for searching for projects? By name, author, even a hash of an existing file. As it stands, it looks like you need to know the project ID before you can do anything.

Great work so far, I look forward to using this.

**Comment by amcoder** [comment]
The Curse Services I'm wrapping don't currently provide a way to search for projects as far as I can tell. Maybe there's something I'm missing though.

The official Curse Client for Windows uses a separate json feed of all the available projects. See: https://github.com/amcoder/Curse.RestProxy/wiki/Curse-Project-Feed

The goal of this project is only to provide a thin wrapper around the Curse WCF services since they are hard to use from a non-.NET environment. The full project feed is a pretty simple json file any client can download, so I was thinking that everyone can use that to get their initial list of projects, then use this to handle the details.

**Comment by Watchful1** [comment]
Perfect, thanks for writing that up for me.
