### ISSUE TITLE
Curse Project Feed outdated.

### ISSUE THREAD

**Issue by Magi1053** [amcoder/Curse.RestProxy#6]
It seems that since July, Curse/Twitch have stopped updating the public json feed, and instead have transitioned into using an separate API gated with an AuthenticationToken.

**Comment by amcoder** [comment]
I have not kept up on the Curse/Twitch changes since Twitch took over. This project is not maintained anymore because I don’t personally use it. I would welcome pull requests or, even better, I’m fine with this being forked and maintained by someone else. 

There are also other projects with the same goal as this one. I believe this one is being maintained. 

https://github.com/dries007/CurseMeta
